### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by sarah872** [pmenzel/score-assemblies#1]
Hi,
I am getting the following error when running `snakemake -k -s score-assemblies/Snakefile --cores 8`

```
NameError in line 69 of /scratch/score-assemblies/Snakefile:
name 'list_nucdiff_stat' is not defined
  File "/scratch/score-assemblies/Snakefile", line 69, in <module>
```

**Comment by pmenzel** [comment]
Hi,

how does your folder structure look like? The README showed a wrong example with nested assembly folders, it is fixed now.

The folders should look like this:
```
.
├── assemblies
│   ├── flye-i4.fa
│   ├── flye-i4+raconx4.fa
│   ├── flye-i4+raconx4+medaka.fa
│   ├── raven-p4.fa
│   └── raven-p4+medaka.fa
│
└── references
    └── bac_sub_ref.fa
```

**Comment by sarah872** [comment]
```
.
├── assemblies
│   ├── ass2.fasta
│   ├── ass2.fasta
│   └── ass1.fasta
└── references
    └── ref-Contigs.fasta
```
But even a dry-run in snakemake doesn't work...

**Comment by pmenzel** [comment]
The fasta files need to be named *.fa.

I could see if both file endings could be accepted in future..

**Comment by sarah872** [comment]
Thank you! It's running now :)
