### ISSUE TITLE
errors in generating report.html

### ISSUE THREAD

**Issue by huyue87** [pmenzel/score-assemblies#4]
Hello!

Very good job! 

However, I met two errors in generating the final report:
One is in lines 95 and 459 from `report.Rmd` 
    `list_breaks <- seq(min(values), second_highest_value, length.out = 10)`
gives a running error of `Error in seq.default(1,data_length) : 'to' must be of length 1`
I assume "second_highest_value" is a NULL, and I changed `sort(unique(values))[n-1]` to `sort(unique(values))[n]` to make the script work. But I am not sure if it is fine to do so. 

The second thing is the QUAST report could not be accessed from the final report.html. 
Instead, I need to be download the QUAST report.html from the quast directory as a renamed file. 

Could you please fix these small issues. Thanks!

**Comment by pmenzel** [comment]
Hi, thanks for testing! :)

Could you try again with the latest version from GitHub? I lately fixed some issues regarding your first error.

The second issue seems to be about that you copy the score-assemblies-report.html to some other place and then open it?
Then you would need to also copy the score-assemblies-data folder for the links in the score-assemblies-report.html to work.

**Comment by pmenzel** [comment]
hi again,
was your issue resolved in the latest version?

**Comment by huyue87** [comment]
> hi again, was your issue resolved in the latest version?

Hi pmenzel!
Sorry for the late reply. And thanks for answering me. 

The latest version works perfectly for single-species comparison (we compared different assemblies of the same species with the species' reference genome). 
Your answer regarding the missing report of QUAST also solved my confusion.
