### ISSUE TITLE
Python Regular Expression

### ISSUE THREAD

**Issue by mweberr** [pmenzel/score-assemblies#8]
Hi, very helpful pipeline to evaluate assemblies. I have problems with understanding your wildcard contraint.
Can you please help ?
[^/\\\\] - A set of characters no slash and no backslash (escaped)

But why is it necessary to have two escaped backslashes in Python Regular Expression ?

Best, Michael

**Comment by pmenzel** [comment]
afair: In the regex itself you need to write `\\` to denote the literal backslash character. And in the python string that describes the regex you also need to do that. Then you end up with `\\\\` for a single backslash.
